<?php

namespace App\Repositories;

use App\Models\Result;
use App\Models\Student;
use App\Repositories\Repository_Interface\ResultRepositoryInterface;
use Illuminate\Pagination\LengthAwarePaginator;

class ResultRepository extends EloquentRepository implements ResultRepositoryInterface
{
    public function getModel()
    {
        return \App\Models\Result::class;
    }

    public function index()
    {
        return parent::getAll();
    }

    public function createResult(array $attribute)
    {
        return parent::create($attribute);
    }

    public function deleteResult($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }

    public function updateResult($id, array $attribute)
    {
        return parent::update($id, $attribute);
    }

    public function massiveUpdateResult($array)
    {

    }
}
