<?php

namespace App\Repositories;

use App\Models\Result;
use App\Models\Student;
use App\Repositories\Repository_Interface\ResultRepositoryInterface;
use Illuminate\Pagination\LengthAwarePaginator;

class ResultRepository extends EloquentRepository implements ResultRepositoryInterface
{
    public function getModel()
    {
        return \App\Models\Result::class;
    }

    public function index()
    {
        return parent::getAll();
    }

    public function createResult(array $attribute)
    {
        return parent::create($attribute);
    }

    public function deleteResult($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }

    public function updateResult($id, array $attribute)
    {
        return parent::update($id, $attribute);
    }

    public function massiveUpdateResult($array)
    {

    }

    public function deleteStudentResult($id)
    {
        $result = Result::where('student_id', '=', $id);
        if ($result) {
            $result->delete();

            return true;
        }

        return false;
    }

    public function deleteSubjectResult($id)
    {
        $result = Result::where('subject_id', '=', $id);
        if ($result) {
            $result->delete();

            return true;
        }

        return false;
    }

    public function getResultByStudentID($id){
        $result = Result::select('results.*','subjects.name')
        ->join('subjects','subjects.id','results.subject_id')
        ->where('student_id','=',$id)->get();
        return $result;
    }
}
